Add Pyhton example
databox/databox-python pull request #20
Opened 2024-09-02 11:13 UTC by tvolge

2024-09-03 08:32 UTC, alekseimi requested changes
Apart from minor issues that detract from the readability of the code, looks good. 

Additionally: The file (module) name `pushData.py` is in camel case. The PEP-8 standard expects snake case, e.g `push_data.py`

Since this is an example, I took the liberty to add additional clarifying comments.

2024-09-03 08:32 UTC, alekseimi commented on examples/pushData/pushData.py
> +from databox.rest import ApiException
Unused import, although we probably should use it when handling exceptions.

2024-09-03 08:32 UTC, alekseimi commented on examples/pushData/pushData.py
> +from pprint import pprint
Unused import.

2024-09-03 08:32 UTC, alekseimi commented on examples/pushData/pushData.py
> +    except Exception as e:
I assume line 15 is raising an `ApiException` for actionable exceptions.

2024-09-03 08:32 UTC, alekseimi commented on examples/pushData/pushData.py
> +        print("Exception: %s\n" % e)
By providing this example, we encourage the use of the ApiException.

```suggestion
    except ApiException as e:
        # Handle exceptions that occur during the API call, such as invalid data or authentication issues
        print("API Exception occurred: %s\n" % e)
    except Exception as e:
        # Handle any other unexpected exceptions
        print("An unexpected error occurred: %s\n" % e)
```

2024-09-03 08:32 UTC, alekseimi commented on examples/pushData/pushData.py
> +
```suggestion
# Configuration setup for the Databox API client
# The API token is used as the username for authentication
# It's recommended to store your API token securely, e.g., in an environment variable
```

2024-09-03 08:32 UTC, alekseimi commented on examples/pushData/pushData.py
> +    push_data = [{"key": "sales2", "value": 100, "unit": "USD", "date": "2021-01-01T00:00:00Z" }]
```suggestion
    # Prepare the data you want to push to Databox
    # The 'key' should match a metric in your Databox account, 'value' is the data point, 'unit' is optional, and 'date' is the timestamp of the data point
    push_data = [{"key": "sales2", "value": 100, "unit": "USD", "date": "2021-01-01T00:00:00Z" }]
```

2024-09-19 13:26 UTC, bwiz approved these changes

2024-09-19 13:27 UTC, alekseimi approved these changes

2024-09-19 13:27 UTC, merged